<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="thread"
    nsURI="http://xored.com/sherlock/thread.ecore" nsPrefix="com.xored.sherlock.thread">
  <eClassifiers xsi:type="ecore:EClass" name="Thread">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ThreadState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ThreadState">
    <eLiterals name="NEW"/>
    <eLiterals name="RUNNABLE" value="1"/>
    <eLiterals name="BLOCKED" value="2"/>
    <eLiterals name="WAITING" value="3"/>
    <eLiterals name="TIMED_WAITING" value="4"/>
    <eLiterals name="TERMINATED" value="5"/>
  </eClassifiers>
</ecore:EPackage>
